_target_: src.data.datamodule.ImageNetWDSDataModule

paths:
  train: ${hydra:runtime.cwd}/datasets/wds_imagenet1k/train/imagenet1k-train-{0000..1023}.tar
  val: ${hydra:runtime.cwd}/datasets/wds_imagenet1k/validation/imagenet1k-validation-{00..63}.tar

batch_size: 512
num_workers: 7
pin_memory: true
persistent_workers: true

input_shape: [3, 224, 224]

normalize:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
