_target_: src.data.datamodule.ImageNetDataModule

data_dir: /home/cameronolson/documents/datasets/imageNetSynthetic
batch_size: 16
num_workers: 7
pin_memory: true
persistent_workers: true

input_shape: [3, 224, 224]
normalize:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
