_target_: src.data.datamodule.ImageNetWDSDataModule

paths:
  train: ${hydra:runtime.cwd}/datasets/wds_imagenet1k/train/{00000..01279}.tar
  val: ${hydra:runtime.cwd}/datasets/wds_imagenet1k/validation/{00000..00049}.tar

batch_size: 512
num_workers: 8
pin_memory: true
persistent_workers: true

input_shape: [3, 224, 224]

normalize:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
