defaults:
   - _self_
   - dataset: cifar10
   - model: resnet_cifar
   - model/block: basic
   - model/stem: cifar
   - optimizer: sgd
   - scheduler: cosine
   - trainer: default
   - training: default
   - experiment: train_cifar_from_scratch

checkpoint:
  resume:
    ckpt_path: /home/cameronolson/documents/projects/ResNet/logs/2025-06-02_19-22-13/resnet_experiments/83vgm0ll/checkpoints/last.ckpt

hydra:
  run:
    dir: logs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: logs/multirun/${now:%Y-%m-%d_%H-%M-%S}
  output_subdir: null
  job:
    chdir: true