defaults:
  - dataset: cifar10
  - model: resnet_cifar
  - optimizer: sgd
  - scheduler: cosine
  - trainer: default
  - training: default
  - experiment: default
  - logger: wandb
  - callbacks: default
  - hydra: default
  - _self_

debug: false
seed: null
mode: train # or resume, finetune
# Can be pytorch or ptl model, depending on what you are doing.
ckpt_path: null
